<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <title>Les domaines par pays</title>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <link rel="stylesheet" type="text/css" href="../../info.css" media="screen">
  <link rel="stylesheet" type="text/css" href="../../print.css" media="print">
  <title>Introduction à l'Internet</title>
</head>
<body>
  <div id="conteneur">
    <div id="texte">
      <h2>Les domaines par pays</h2>
      <table cellspacing="4" cellpadding="1">
        <tr>
          <td>Ascension</td>
          <td>.ac</td>
        </tr>
        <tr>
          <td>Andorre</td>
          <td>.ad</td>
        </tr>
        <tr>
          <td>Emirats Arabes Unis</td>
          <td>.ae</td>
        </tr>
        <tr>
          <td>Afganistan</td>
          <td>.af</td>
        </tr>
        <tr>
          <td>Antigua And Barbuda</td>
          <td>.ag</td>
        </tr>
        <tr>
          <td>Anguilla</td>
          <td>.ai</td>
        </tr>
        <tr>
          <td>Albanie</td>
          <td>.al</td>
        </tr>
        <tr>
          <td>Arménie</td>
          <td>.am</td>
        </tr>
        <tr>
          <td>Netherlands Antilles</td>
          <td>.an</td>
        </tr>
        <tr>
          <td>Angola</td>
          <td>.ao</td>
        </tr>
        <tr>
          <td>Antartique</td>
          <td>.aq</td>
        </tr>
        <tr>
          <td>Argentine</td>
          <td>.ar</td>
        </tr>
        <tr>
          <td>American Samoa</td>
          <td>.as</td>
        </tr>
        <tr>
          <td>Autriche</td>
          <td>.at</td>
        </tr>
        <tr>
          <td>Australie</td>
          <td>.au</td>
        </tr>
        <tr>
          <td>Aruba</td>
          <td>.aw</td>
        </tr>
        <tr>
          <td>Azerbaidjan</td>
          <td>.az</td>
        </tr>
        <tr>
          <td>Bosnie Herzégovine</td>
          <td>.ba</td>
        </tr>
        <tr>
          <td>Barbades</td>
          <td>.bb</td>
        </tr>
        <tr>
          <td>Bangladesh</td>
          <td>.bd</td>
        </tr>
        <tr>
          <td>Belgique</td>
          <td>.be</td>
        </tr>
        <tr>
          <td>Burkina Faso</td>
          <td>.bf</td>
        </tr>
        <tr>
          <td>Bulgarie</td>
          <td>.bg</td>
        </tr>
        <tr>
          <td>Bahrain</td>
          <td>.bh</td>
        </tr>
        <tr>
          <td>Burundi</td>
          <td>.bi</td>
        </tr>
        <tr>
          <td>Benin</td>
          <td>.bj</td>
        </tr>
        <tr>
          <td>Bermudes</td>
          <td>.bm</td>
        </tr>
        <tr>
          <td>Brunei Darussalam</td>
          <td>.bn</td>
        </tr>
        <tr>
          <td>Bolivie</td>
          <td>.bo</td>
        </tr>
        <tr>
          <td>Brésil</td>
          <td>.br</td>
        </tr>
        <tr>
          <td>Bahamas</td>
          <td>.bs</td>
        </tr>
        <tr>
          <td>Buthan</td>
          <td>.bt</td>
        </tr>
        <tr>
          <td>Bouvet Island</td>
          <td>.bv</td>
        </tr>
        <tr>
          <td>Botswana</td>
          <td>.bw</td>
        </tr>
        <tr>
          <td>Bélarus</td>
          <td>.by</td>
        </tr>
        <tr>
          <td>Belize</td>
          <td>.bz</td>
        </tr>
        <tr>
          <td>Canada</td>
          <td>.ca</td>
        </tr>
        <tr>
          <td>Cocos Islands</td>
          <td>.cc</td>
        </tr>
        <tr>
          <td>République du Congo</td>
          <td>.cd</td>
        </tr>
        <tr>
          <td>République d'Afrique Centrale</td>
          <td>.cf</td>
        </tr>
        <tr>
          <td>Congo</td>
          <td>.cg</td>
        </tr>
        <tr>
          <td>Suisse</td>
          <td>.ch</td>
        </tr>
        <tr>
          <td>Côte d'Ivoire</td>
          <td>.ci</td>
        </tr>
        <tr>
          <td>Iles Cook</td>
          <td>.ck</td>
        </tr>
        <tr>
          <td>Chili</td>
          <td>.cl</td>
        </tr>
        <tr>
          <td>Cameroun</td>
          <td>.cm</td>
        </tr>
        <tr>
          <td>Chine</td>
          <td>.cn</td>
        </tr>
        <tr>
          <td>Colombie</td>
          <td>.co</td>
        </tr>
        <tr>
          <td>Costa Rica</td>
          <td>.cr</td>
        </tr>
        <tr>
          <td>Cuba</td>
          <td>.cu</td>
        </tr>
        <tr>
          <td>Cap Vert</td>
          <td>.cv</td>
        </tr>
        <tr>
          <td>Christmas Island</td>
          <td>.cx</td>
        </tr>
        <tr>
          <td>Chypre</td>
          <td>.cy</td>
        </tr>
        <tr>
          <td>République Tchèque</td>
          <td>.cz</td>
        </tr>
        <tr>
          <td>Allemagne</td>
          <td>.de</td>
        </tr>
        <tr>
          <td>Djibouti</td>
          <td>.dj</td>
        </tr>
        <tr>
          <td>Danmark</td>
          <td>.dk</td>
        </tr>
        <tr>
          <td>Dominica</td>
          <td>.dm</td>
        </tr>
        <tr>
          <td>République Dominicaine</td>
          <td>.do</td>
        </tr>
        <tr>
          <td>Algérie</td>
          <td>.dz</td>
        </tr>
        <tr>
          <td>Equateur</td>
          <td>.ec</td>
        </tr>
        <tr>
          <td>Estonie</td>
          <td>.ee</td>
        </tr>
        <tr>
          <td>Egypte</td>
          <td>.eg</td>
        </tr>
        <tr>
          <td>Sahara occidental</td>
          <td>.eh</td>
        </tr>
        <tr>
          <td>Erytrée</td>
          <td>.er</td>
        </tr>
        <tr>
          <td>Espagne</td>
          <td>.es</td>
        </tr>
        <tr>
          <td>Ethiopie</td>
          <td>.et</td>
        </tr>
        <tr>
          <td>Finlande</td>
          <td>.fi</td>
        </tr>
        <tr>
          <td>Fidji</td>
          <td>.fj</td>
        </tr>
        <tr>
          <td>Iles Fakland (Malouines)</td>
          <td>.fk</td>
        </tr>
        <tr>
          <td>Micronesie (Etat Fédéral)</td>
          <td>.fm</td>
        </tr>
        <tr>
          <td>Iles Faroe</td>
          <td>.fo</td>
        </tr>
        <tr>
          <td>France</td>
          <td>.fr</td>
        </tr>
        <tr>
          <td>France Métropoliotaine</td>
          <td>.fx</td>
        </tr>
        <tr>
          <td>Gabon</td>
          <td>.ga</td>
        </tr>
        <tr>
          <td>Grande Bretagne</td>
          <td>.gb</td>
        </tr>
        <tr>
          <td>Grenade</td>
          <td>.gd</td>
        </tr>
        <tr>
          <td>Géorgie</td>
          <td>.ge</td>
        </tr>
        <tr>
          <td>Guyane Française</td>
          <td>.gf</td>
        </tr>
        <tr>
          <td>Ghana</td>
          <td>.gh</td>
        </tr>
        <tr>
          <td>Gibraltar</td>
          <td>.gi</td>
        </tr>
        <tr>
          <td>Groenland</td>
          <td>.gl</td>
        </tr>
        <tr>
          <td>Gambie</td>
          <td>.gm</td>
        </tr>
        <tr>
          <td>Guinée</td>
          <td>.gn</td>
        </tr>
        <tr>
          <td>Guadeloupe</td>
          <td>.gp</td>
        </tr>
        <tr>
          <td>Guinéee Equatoriale</td>
          <td>.gq</td>
        </tr>
        <tr>
          <td>Grèce</td>
          <td>.gr</td>
        </tr>
        <tr>
          <td>South Georgia and the</td>
          <td>.gs</td>
        </tr>
        <tr>
          <td>Guatemala</td>
          <td>.gt</td>
        </tr>
        <tr>
          <td>Ile de Guam</td>
          <td>.gu</td>
        </tr>
        <tr>
          <td>Guiné-Bissau</td>
          <td>.gw</td>
        </tr>
        <tr>
          <td>Guyane</td>
          <td>.gy</td>
        </tr>
        <tr>
          <td>Hong Kong</td>
          <td>.hk</td>
        </tr>
        <tr>
          <td>Heard and Mc Donald</td>
          <td>.hm</td>
        </tr>
        <tr>
          <td>Honduras</td>
          <td>.hn</td>
        </tr>
        <tr>
          <td>Croatie</td>
          <td>.hr</td>
        </tr>
        <tr>
          <td>Haiti</td>
          <td>.ht</td>
        </tr>
        <tr>
          <td>Hongrie</td>
          <td>.he</td>
        </tr>
        <tr>
          <td>Indonésie</td>
          <td>.id</td>
        </tr>
        <tr>
          <td>Irelande</td>
          <td>.ie</td>
        </tr>
        <tr>
          <td>Israël</td>
          <td>.il</td>
        </tr>
        <tr>
          <td>Inde</td>
          <td>.in</td>
        </tr>
        <tr>
          <td>Territoire Anglais de l'Océan Indien</td>
          <td>.io</td>
        </tr>
        <tr>
          <td>Irak</td>
          <td>.iq</td>
        </tr>
        <tr>
          <td>Iran</td>
          <td>.ir</td>
        </tr>
        <tr>
          <td>Islande</td>
          <td>.is</td>
        </tr>
        <tr>
          <td>Italie</td>
          <td>.it</td>
        </tr>
        <tr>
          <td>Jamaïque</td>
          <td>.jm</td>
        </tr>
        <tr>
          <td>Jordanie</td>
          <td>.jo</td>
        </tr>
        <tr>
          <td>Japon</td>
          <td>.jp</td>
        </tr>
        <tr>
          <td>Kenya</td>
          <td>.ke</td>
        </tr>
        <tr>
          <td>Kyrgyzstan</td>
          <td>.kg</td>
        </tr>
        <tr>
          <td>Cambodge</td>
          <td>.kh</td>
        </tr>
        <tr>
          <td>Kiribati</td>
          <td>.ki</td>
        </tr>
        <tr>
          <td>Iles Comores</td>
          <td>.km</td>
        </tr>
        <tr>
          <td>Saint Kitts and Nevis</td>
          <td>.kn</td>
        </tr>
        <tr>
          <td>République Démocratique populaire de Corée</td>
          <td>.kp</td>
        </tr>
        <tr>
          <td>République de Corée</td>
          <td>.kr</td>
        </tr>
        <tr>
          <td>Koweit</td>
          <td>.kw</td>
        </tr>
        <tr>
          <td>Iles Cayman</td>
          <td>.ky</td>
        </tr>
        <tr>
          <td>Kazakstan</td>
          <td>.kz</td>
        </tr>
        <tr>
          <td>Laos</td>
          <td>.la</td>
        </tr>
        <tr>
          <td>Liban</td>
          <td>.lb</td>
        </tr>
        <tr>
          <td>Sainte Lucie</td>
          <td>.lc</td>
        </tr>
        <tr>
          <td>Liechtenstein</td>
          <td>.li</td>
        </tr>
        <tr>
          <td>Sri Lanka</td>
          <td>.lk</td>
        </tr>
        <tr>
          <td>Liberia</td>
          <td>.lr</td>
        </tr>
        <tr>
          <td>Lesotho</td>
          <td>.ls</td>
        </tr>
        <tr>
          <td>Lituanie</td>
          <td>.lt</td>
        </tr>
        <tr>
          <td>Luxembourg</td>
          <td>.lu</td>
        </tr>
        <tr>
          <td>Latvia</td>
          <td>.lv</td>
        </tr>
        <tr>
          <td>Libyan Arab Jamahiriya</td>
          <td>.ly</td>
        </tr>
        <tr>
          <td>Maroc</td>
          <td>.ma</td>
        </tr>
        <tr>
          <td>Monaco</td>
          <td>.mc</td>
        </tr>
        <tr>
          <td>Moldavie</td>
          <td>.md</td>
        </tr>
        <tr>
          <td>Madagascar</td>
          <td>.mg</td>
        </tr>
        <tr>
          <td>Iles Marshall</td>
          <td>.mh</td>
        </tr>
        <tr>
          <td>Macédoine</td>
          <td>.mk</td>
        </tr>
        <tr>
          <td>Mali</td>
          <td>.ml</td>
        </tr>
        <tr>
          <td>Myanmar</td>
          <td>.mm</td>
        </tr>
        <tr>
          <td>Mongolie</td>
          <td>.mn</td>
        </tr>
        <tr>
          <td>Macao</td>
          <td>.mo</td>
        </tr>
        <tr>
          <td>Iles Mariannes du Nord</td>
          <td>.mp</td>
        </tr>
        <tr>
          <td>Martinique</td>
          <td>.mq</td>
        </tr>
        <tr>
          <td>Mauritanie</td>
          <td>.mr</td>
        </tr>
        <tr>
          <td>Monserrat</td>
          <td>.ms</td>
        </tr>
        <tr>
          <td>Malte</td>
          <td>.mt</td>
        </tr>
        <tr>
          <td>Mauritanie</td>
          <td>.mu</td>
        </tr>
        <tr>
          <td>Maldives</td>
          <td>.mv</td>
        </tr>
        <tr>
          <td>Malawi</td>
          <td>.mw</td>
        </tr>
        <tr>
          <td>Mexique</td>
          <td>.mx</td>
        </tr>
        <tr>
          <td>Malaisie</td>
          <td>.my</td>
        </tr>
        <tr>
          <td>Mozambique</td>
          <td>.mz</td>
        </tr>
        <tr>
          <td>Namibie</td>
          <td>.na</td>
        </tr>
        <tr>
          <td>Nouvelle Calédonie</td>
          <td>.nc</td>
        </tr>
        <tr>
          <td>Niger</td>
          <td>.ne</td>
        </tr>
        <tr>
          <td>Iles Norfolk</td>
          <td>.nf</td>
        </tr>
        <tr>
          <td>Nigeria</td>
          <td>.ng</td>
        </tr>
        <tr>
          <td>Nicaragua</td>
          <td>.ni</td>
        </tr>
        <tr>
          <td>Hollande</td>
          <td>.nl</td>
        </tr>
        <tr>
          <td>Norvège</td>
          <td>.no</td>
        </tr>
        <tr>
          <td>Népal</td>
          <td>.np</td>
        </tr>
        <tr>
          <td>Nauru</td>
          <td>.nr</td>
        </tr>
        <tr>
          <td>Niue</td>
          <td>.nu</td>
        </tr>
        <tr>
          <td>Nouvelle Zélande</td>
          <td>.nz</td>
        </tr>
        <tr>
          <td>Oman</td>
          <td>.om</td>
        </tr>
        <tr>
          <td>Panama</td>
          <td>.pa</td>
        </tr>
        <tr>
          <td>Pérou</td>
          <td>.pe</td>
        </tr>
        <tr>
          <td>Polynésie Française</td>
          <td>.pf</td>
        </tr>
        <tr>
          <td>Papouasie Nouvelle Guinée</td>
          <td>.pg</td>
        </tr>
        <tr>
          <td>Philippines</td>
          <td>.ph</td>
        </tr>
        <tr>
          <td>Pakistan</td>
          <td>.pk</td>
        </tr>
        <tr>
          <td>Pologne</td>
          <td>.pl</td>
        </tr>
        <tr>
          <td>Saint Pierre et Miquelon</td>
          <td>.pm</td>
        </tr>
        <tr>
          <td>Pitcairn</td>
          <td>.pn</td>
        </tr>
        <tr>
          <td>Porto Rico</td>
          <td>.pr</td>
        </tr>
        <tr>
          <td>Portugal</td>
          <td>.pt</td>
        </tr>
        <tr>
          <td>Palau</td>
          <td>.pw</td>
        </tr>
        <tr>
          <td>Paraguay</td>
          <td>.py</td>
        </tr>
        <tr>
          <td>Quatar</td>
          <td>.qa</td>
        </tr>
        <tr>
          <td>Réunion</td>
          <td>.re</td>
        </tr>
        <tr>
          <td>Roumanie</td>
          <td>.ro</td>
        </tr>
        <tr>
          <td>Fédération Russe</td>
          <td>.ru</td>
        </tr>
        <tr>
          <td>Rwanda</td>
          <td>.rw</td>
        </tr>
        <tr>
          <td>Arabie Saoudite</td>
          <td>.sa</td>
        </tr>
        <tr>
          <td>Iles Salomon</td>
          <td>.sb</td>
        </tr>
        <tr>
          <td>Seychelles</td>
          <td>.sc</td>
        </tr>
        <tr>
          <td>Soudan</td>
          <td>.sd</td>
        </tr>
        <tr>
          <td>Suède</td>
          <td>.se</td>
        </tr>
        <tr>
          <td>Singapour</td>
          <td>.sg</td>
        </tr>
        <tr>
          <td>Sainte Hélène</td>
          <td>.sh</td>
        </tr>
        <tr>
          <td>Slovanie</td>
          <td>.si</td>
        </tr>
        <tr>
          <td>Slovaquie</td>
          <td>.sk</td>
        </tr>
        <tr>
          <td>Sierra Leone</td>
          <td>.sl</td>
        </tr>
        <tr>
          <td>San Marin</td>
          <td>.sm</td>
        </tr>
        <tr>
          <td>Sénégal</td>
          <td>.sn</td>
        </tr>
        <tr>
          <td>Somalie</td>
          <td>.so</td>
        </tr>
        <tr>
          <td>Surinam</td>
          <td>.sr</td>
        </tr>
        <tr>
          <td>Sao Tome And Principe</td>
          <td>.st</td>
        </tr>
        <tr>
          <td>Salvador</td>
          <td>.sv</td>
        </tr>
        <tr>
          <td>Syrie</td>
          <td>.sy</td>
        </tr>
        <tr>
          <td>Swaziland</td>
          <td>.sz</td>
        </tr>
        <tr>
          <td>Iles Turques et Caicos</td>
          <td>.tc</td>
        </tr>
        <tr>
          <td>Tchad</td>
          <td>.td</td>
        </tr>
        <tr>
          <td>Territoire Français du Sud</td>
          <td>.tf</td>
        </tr>
        <tr>
          <td>Togo</td>
          <td>.tg</td>
        </tr>
        <tr>
          <td>Thailande</td>
          <td>.th</td>
        </tr>
        <tr>
          <td>Tadjikistan</td>
          <td>.tj</td>
        </tr>
        <tr>
          <td>Tokelau</td>
          <td>.tk</td>
        </tr>
        <tr>
          <td>Turkménistan</td>
          <td>.tm</td>
        </tr>
        <tr>
          <td>Tunisie</td>
          <td>.tn</td>
        </tr>
        <tr>
          <td>Iles Tonga</td>
          <td>.to</td>
        </tr>
        <tr>
          <td>Timor Oriental</td>
          <td>.tp</td>
        </tr>
        <tr>
          <td>Turquie</td>
          <td>.tr</td>
        </tr>
        <tr>
          <td>Tuvalu</td>
          <td>.tv</td>
        </tr>
        <tr>
          <td>Taiwan</td>
          <td>.tw</td>
        </tr>
        <tr>
          <td>Tanzanie</td>
          <td>.tz</td>
        </tr>
        <tr>
          <td>Ukraine</td>
          <td>.ua</td>
        </tr>
        <tr>
          <td>Ouganda</td>
          <td>.ug</td>
        </tr>
        <tr>
          <td>Royaume Uni</td>
          <td>.uk</td>
        </tr>
        <tr>
          <td>USA</td>
          <td>.us</td>
        </tr>
        <tr>
          <td>Uruguay</td>
          <td>.uy</td>
        </tr>
        <tr>
          <td>Ouzbekistan</td>
          <td>.uz</td>
        </tr>
        <tr>
          <td>Vatican</td>
          <td>.va</td>
        </tr>
        <tr>
          <td>Iles Grenadines et St Vincent</td>
          <td>.vc</td>
        </tr>
        <tr>
          <td>Vénézuela</td>
          <td>.ve</td>
        </tr>
        <tr>
          <td>Iles Vierges Anglaises</td>
          <td>.vg</td>
        </tr>
        <tr>
          <td>Iles Vierges Américaines</td>
          <td>.vi</td>
        </tr>
        <tr>
          <td>VietNam</td>
          <td>.vn</td>
        </tr>
        <tr>
          <td>Vanuatu</td>
          <td>.vu</td>
        </tr>
        <tr>
          <td>Wallis et Futuna</td>
          <td>.wf</td>
        </tr>
        <tr>
          <td>Samoa</td>
          <td>.ws</td>
        </tr>
        <tr>
          <td>Yemen</td>
          <td>.ye</td>
        </tr>
        <tr>
          <td>Mayotte</td>
          <td>.yt</td>
        </tr>
        <tr>
          <td>Yougoslavie</td>
          <td>.yu</td>
        </tr>
        <tr>
          <td>Afrique Du sud</td>
          <td>.za</td>
        </tr>
        <tr>
          <td>Zambie</td>
          <td>.zm</td>
        </tr>
        <tr>
          <td>Zimbabwe</td>
          <td>.zw</td>
        </tr>
      </table>
    </div>
  </div>
</body>
</html>
