<?php // Generated by Nvu + HandCoder ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta name="generator"
 content="HTML Tidy for Windows (vers 12 April 2005), see www.w3.org">
  <meta http-equiv="Content-Type"
 content="text/html; charset=iso-8859-1">
  <link rel="stylesheet" type="text/css" href="../../info.css"
 media="screen">
  <link rel="stylesheet" type="text/css" href="../../print.css"
 media="print">
  <title>La sécurité informatique</title>
</head>
<body>
<div id="conteneur">
<?php include ("./top.inc.php");?>
<div id="texte">
<div style="background-color: rgb(255, 255, 204);" class="encartdroit">
<h3><img class="imagedroite" style="width: 237px; height: 178px;"
 alt="Pauvre Julie" src="images/gargl.png">Flash
Info</h3>
&nbsp;Julie s'apprêtait à
terminer son travail de fin
d'études à remettre la semaine prochaine. Son ordinateur s'est soudain
éteint et il ne cesse maintenant de redémarrer&nbsp;; il est devenu
incontrôlable. Le travail de fin d'études est devenu inaccessible.
Comment est-ce possible&nbsp;? </div>
<h2> Qu'est-ce
qu'un virus informatique&nbsp;? </h2>
<div class="info">
<p> Un virus informatique est semblable à un virus
biologique.&nbsp;</p>
<p>Tout virus biologique a besoin d'une cellule à
infecter pour
pouvoir
se reproduire et se disséminer dans son environnement.&nbsp;</p>
<p>Un
virus
informatique a besoin d'un programme exécutable pour se
reproduire et
se disséminer dans son environnement. </p>
</div>
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
 codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0"
 class="imagedroite" height="504" width="530"> <param name="movie"
 value="images/virus.swf"> <param name="quality" value="high">
<embed style="border: 1px solid rgb(255, 255, 0);"
 src="images/virus.swf" quality="high"
 pluginspage="http://www.macromedia.com/go/getflashplayer"
 type="application/x-shockwave-flash" height="504" width="530">
<embed> </object>
<h3>Action d'un virus biologique</h3>
<div class="travail">
<ul>
  <li>Observe
l'animation ci-dessous.</li>
  <li>Vérifie
qu'elle correspond bien à l'explication donnée en vis-à-vis.</li>
</ul>
</div>
<p>Les virus biologiques (le virus de la grippe, par exemple) se
propagent aux dépens des cellules qu'ils infectent. Ils n'ont
aucun
autre moyen de se reproduire. </p>
<ul>
  <li>Le virus injecte son matériel génétique (ADN
ou ARN) dans une
cellule. </li>
  <li>Le matériel génétique rejoint le noyau
cellulaire. </li>
  <li>Sur la base des plans que constituent l'ADN ou
l'ARN du virus, la
cellule se met à fabriquer de nouveaux virus. </li>
  <li>Ces virus
peuvent, à leur tour, infecter une nouvelle
cellule en
utilisant le même mode de propagation. </li>
</ul>
<p> La particularité des virus est qu'il ne peuvent se
reproduire sans
l'aide d'une cellule vivante. </p>
<h3> Action d'un virus informatique </h3>
<p> Un virus informatique agit selon une méthode tout à
fait semblable
au virus biologique. C'est d'ailleurs pour cette raison que ce type de
programme a été appelé "&nbsp;virus&nbsp;".</p>
<div class="travail">
<ul>
  <li>Observe
l'animation ci-dessous.</li>
  <li>Vérifie qu'elle correspond bien à
l'explication donnée.</li>
</ul>
</div>
<p> <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
 codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0"
 name="virus" class="imagedroite" id="virus" height="301" width="530"> <param
 name="movie" value="images/infectivir.swf"> <param name="quality"
 value="high">
<embed src="images/infectivir.swf" quality="high"
 pluginspage="http://www.macromedia.com/go/getflashplayer"
 type="application/x-shockwave-flash" name="virus" height="301"
 width="530"> </object> </p>
<ul>
  <li>Le virus informatique injecte
le code dont il est formé
dans le
code d'un programme qu'il trouve sur l'ordinateur cible. </li>
  <li>Lorsque
le programme infecté est exécuté, le
virus se reproduit
et infecte, à nouveau, un ou plusieurs autres programmes. </li>
</ul>
<p> La particularité des virus informatiques est qu'ils ne
peuvent se
reproduire sans l'aide d'un programme&nbsp;existant. </p>
<p class="questions"> Mais il y a un truc qui ne va pas, dans votre
système&nbsp;! Comment le virus peut-il arriver dans mon
ordinateur
puisqu'il a besoin d'un programme à infecter et ne peut se
transmettre
que par cette voie&nbsp;? </p>
<p class="reponses"> Conclusion&nbsp;: un virus arrive toujours dans un
fichier exécutable par l'ordinateur. Il faut donc toujours se
méfier de
ce type de fichiers. </p>
<fieldset><legend
 style="font-weight: bold; background-color: red; color: white;">À
retenir</legend>
<p> En informatique, un " Virus " est un logiciel malveillant qui se
propage en se cachant dans d'autres logiciels.</p>
<p>Lorsque le logiciel infecté est activé, le virus s'active aussi. Il
tente alors de se multiplier et&nbsp;commence son travail de
destruction dans l'ordinateur infecté.</p>
</fieldset>
<form class="travail" action=""> Dans un programme infecté par
un virus,
on trouve généralement&nbsp;:<br>
  <input name="bt"
 onclick="alert('Non.\nNe s\'agit-il pas alors d\'un virus biologique?')"
 type="radio"> L'ADN du virus<br>
  <input name="bt"
 onclick="alert('Exact.\nLe programme infecté contient le code du virus. Cela signifie que l\'exécution du programme provoquera probablement l\'activation du virus.')"
 type="radio"> Le code du virus lui-même<br>
  <input name="bt"
 onclick="alert('Réponse fausse.\nCe programme infecté a acquis une particularité')"
 type="radio"> Rien de particulier </form>
<form class="travail" action=""> Un virus informatique est<br>
  <input name="bt"
 onclick="alert('Exact.\nUn virus est un programme d\'ordinateur capable de se reproduire et de causer des dégâts dans un ordinateur.')"
 type="radio"> Un programme d'ordinateur<br>
  <input name="bt"
 onclick="alert('Non.\nIl s\'agit là d\'un virus biologique.')"
 type="radio"> Une particule plus petite qu'une cellule<br>
  <input name="bt"
 onclick="alert('Réponse fausse.\nOn trouve de l\'ADN ou de l\'ARN dans les virus biologiques.')"
 type="radio"> Un fragment d'ADN ou d'ARN </form>
<form class="travail" action=""> Pour pouvoir se propager, un virus
informatique a besoin de<br>
  <input name="bt"
 onclick="alert('Exact.\nLe virus va tenter de s\'introduire dans un programme.\nChaque fois que ce programme sera exécuté, le virus s\'activera.')"
 type="radio"> Un programme cible<br>
  <input name="bt"
 onclick="alert('Non.\nTu sembles confondre le virus informatique avec le virus biologique.')"
 type="radio"> Une cellule cible<br>
  <input name="bt"
 onclick="alert('Réponse fausse.\nPour pouvoir se propager, un virus a besoin d\'un \&quot;vecteur\&quot;. Lequel?')"
 type="radio"> Rien de particulier </form>
<form class="travail" action=""> En général, quand un
virus a infecté un
ordinateur<br>
  <input name="bt"
 onclick="alert('Non.\nEn général, les virus tentent de se reproduire.')"
 type="radio"> Il devient inactif<br>
  <input name="bt"
 onclick="alert('Exact.\nDès que le programme qui contient le virus est activé, le virus tente de se reproduire.')"
 type="radio"> Il tente de se reproduire<br>
  <input name="bt"
 onclick="alert('Faux.\nUne des activités d\'un virus est bien de se reproduire.')"
 type="radio"> Il reste actif mais est incapable de se reproduire </form>
<p>Quand tu as répondu à toutes les questions et bien
compris les
réponses, passe à la page suivante.<?php include ("../../psuivante.inc.php");
?></p>
</div>
<?php include ("../../pied.inc.php");
include ("../../stat.inc.php");
?></div>
</body>
</html>
