<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html><head><?php // Generated by Nvu + HandCoder ?>


<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet" type="text/css" href="../../info.css" media="screen"> <link rel="stylesheet" type="text/css" href="../../print.css" media="print"><title>La sécurité informatique</title></head><body><div id="conteneur">
<?php include ("./top.inc.php");?>
<div id="texte">
<h2>Plan de la leçon </h2>
<ol> <li><a href="1.php">Pourquoi cette leçon sur la
sécurité&nbsp;?</a></li> <li><a href="2.php">Qu'est-ce qu'un virus
informatique&nbsp;?</a></li> <li><a href="3.php">Reconnaître les
fichiers exécutables</a></li> <li><a href="4.php">Que font les virus
informatiques&nbsp;?</a></li> <li><a href="5.php">Pourquoi les virus
informatiques&nbsp;?</a></li> <li><a href="6.php">Quelle différence
entre un ver et un
virus&nbsp;?</a></li> <li><a href="7.php">Les Chevaux de Troie</a></li>
<li><a href="8.php">Autres nuisances logicielles&nbsp;: spywares,
adwares, keyloggers, dialers</a></li> <li><a href="9.php">Le
"&nbsp;phishing&nbsp;"</a></li> <li><a href="10.php">Le
"&nbsp;spamming&nbsp;"</a></li> <li><a href="11.php">Autres dangers et
pestes de l'Internet&nbsp;:
intrusions, hoaxes et comportement</a></li>
  <li><a href="12.php">La cyberguerre fait rage sur l'Internet</a><br>
  </li>
<li><a href="13.php">Ton
avis m'intéresse</a> </li>
</ol><?php include ("../../psuivante.inc.php");
include ("../../pied.inc.php");
include ("../../stat.inc.php");
?>
</div></div></body></html>