<?php // Generated by Nvu + HandCoder ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet" type="text/css" href="../../info.css"
 media="screen"> <link rel="stylesheet" type="text/css"
 href="../../print.css" media="print"> <title>La sécurité informatique</title></head>
<body><div id="conteneur">
<div id="texte">
<?php include ("./top.inc.php"); ?>
<h2>Plan de la leçon </h2>
<ol>
<li><a href="1.php">Comment se protéger des dangers de l'Internet?</a></li> 
<li><a href="2.php">Les antivirus</a></li> 
<li><a href="3.php">Le pare-feu (ou "&nbsp;firewall&nbsp;")</a></li> 
<li><a href="4.php">Contre les "&nbsp;adwares&nbsp;" et les "&nbsp;spywares&nbsp;"</a></li> 
<li><a href="5.php">Contre les spams</a></li>
<li><a href="6.php">Derniers conseils</a></li> 
<li><a href="7.php">Quelques questions</a></li> 
<li><a href="8.php">Ton avis m'intéresse</a> </li>
</ol>
<?php include ("../../psuivante.inc.php");
include ("../../pied.inc.php");
include ("../../stat.inc.php");
?>
</div></div></body></html>